@{
    # Single source of truth for public, inherited WinUI base-class properties that Ether's
    # custom control templates do NOT consume. Consumers can set these: the build succeeds,
    # nothing throws, and nothing happens on screen (or, for EtherDropdown.Text/IsEditable,
    # nothing happens functionally either).
    #
    # scripts/Verify-UnsupportedProperties.ps1 asserts every entry below is genuinely
    # zero-consumption in the named template file(s), and that docs/consumers/getting-started.md
    # documents the exact same property list. Both the gate and the docs read this file; there
    # is no second copy of the list anywhere else. If someone later implements one of these
    # properties, remove its entry here (the gate will otherwise start failing the moment the
    # implementation lands, because the template file will then contain the binding this file
    # asserts is absent).
    #
    # ============================================================================================
    # R-07: THIS FILE HAS TWO SECTIONS - a CLOSED list and an OPEN one.
    # (see docs/plans/2026-08-31-release-blockers-spec.md, section R-07, for the full history -
    # do not edit that spec file; this comment is the operative account of what the code does.)
    #
    #   Entries (below) - CLOSED allowlist, exactly 12 "trap" properties: consumer-facing
    #     functional/decoration properties (Header, HeaderTemplate, Description, PlaceholderText,
    #     PlaceholderForeground, Text, IsEditable) on EtherDropdown/EtherInput/EtherSwitch that a
    #     consumer would REASONABLY expect to work but that silently do nothing.
    #     scripts/Verify-UnsupportedProperties.ps1 statically re-checks only THESE 12 - it cannot
    #     discover a 13th silently-ineffective property, by design (it is a regression guard for
    #     known traps, not a scanner). Do not add new entries here without also adding an
    #     Alternative and updating docs/consumers/getting-started.md's machine-checked table -
    #     this list must stay hand-curated and small; that is what keeps every entry in it a
    #     genuine "a reasonable consumer would expect this to work" trap.
    #
    #   AcknowledgedSilent (below Entries) - OPEN accounting of every OTHER public, inherited
    #     property that the newest artifacts/audit-runs/consumer-runtime-evidence-*/
    #     runtime-result.json classifies as Method == 'platform-dp-contract': the DP getter/
    #     setter round-trips without throwing on an attached, rendered control, but the control's
    #     RenderTargetBitmap is pixel-for-pixel identical before and after - i.e. the property is
    #     publicly writable and inherited from a WinUI base class, but Ether's fixed control
    #     template does not consume it anywhere. As of the newest evidence run
    #     (consumer-runtime-evidence-20260831-033043851), that is 156 properties; 10 of those 156
    #     are already covered by the 12 Entries above (the other 2 Entries, EtherSwitch.Header/
    #     HeaderTemplate, do not appear in this evidence at all because EtherSwitch is a keyed
    #     Style applied to a stock ToggleSwitch, not a distinct type the runtime harness attaches
    #     evidence to by name) - leaving 146 properties accounted for here.
    #
    #     R-07 decision #2 (see the spec file) is that NONE of these 156 properties get wired up
    #     in this pass - this is a design system, and appearance is intentionally not overridable
    #     by consumers, so the engineering deliverable is DETECTION + ACCOUNTING, not
    #     implementation.
    #
    #   ------------------------------------------------------------------------------------------
    #   R-07 REFINEMENT (2026-08-31): the FIRST cut of this file bucketed every AcknowledgedSilent
    #   entry as either 'design-system-owned' or 'platform-noop' purely from evidence Method ==
    #   'platform-dp-contract' (RenderTargetBitmap unchanged). That conflates three DIFFERENT
    #   things under one label: (a) a property genuinely not wired to anything, (b) a property
    #   the template DOES consume via {TemplateBinding X} where the visual gate's specific probe
    #   just didn't produce a pixel difference, and (c) a behavioral/content property the WinUI
    #   BASE CLASS honors internally regardless of template (e.g. TextBox's own Enter-key/
    #   read-only/casing handling). Concretely: EtherInput.PlaceholderText and
    #   EtherInput.PlaceholderForeground DO have `{TemplateBinding PlaceholderText}` /
    #   `{TemplateBinding PlaceholderForeground}` in EtherInput.xaml (they render the placeholder
    #   TextBlock) - calling them "silently ineffective" was FALSE. Same bug applied to several
    #   more *ContentAlignment/FontFamily/FontSize/BorderBrush/BorderThickness properties across
    #   EtherButton/EtherDropdown/EtherIntelligenceButton/EtherMasthead/EtherSegmentedControl (all
    #   genuinely template-bound), and to EtherInput.AcceptsReturn/CharacterCasing/IsReadOnly and
    #   EtherProgressBar.IsEnabled (all genuinely functional via base-class behavior). "The visual
    #   gate saw no pixel change" is evidence of "not template-consumed", NOT proof of "does
    #   nothing" - this file's Bucket values now reflect that distinction instead of erasing it.
    #
    #   Every AcknowledgedSilent entry carries a Bucket, one of FIVE (mechanically distinguished,
    #   not judgment calls, via the TemplateBinding cross-check described below):
    #
    #     'design-system-owned' - an appearance property (Background/Border*/CornerRadius/Padding/
    #       Foreground/Font*/CharacterSpacing/*ContentAlignment family - same family list as
    #       before) with NO `{TemplateBinding <Property>}` anywhere in the control's
    #       TemplateFiles[Control] entry (see below). Genuinely not honored: the design system
    #       deliberately does not let consumers override it, to keep the visual language
    #       consistent across every app that consumes it ("no visible effect" is a FEATURE here,
    #       not a defect). THIS is the only bucket that means "silently ineffective by design".
    #
    #     'consumed-visually-stable' - the property DOES have a `{TemplateBinding <Property>}` in
    #       TemplateFiles[Control] (verified per-entry, with file:line, in each Reason). It IS
    #       consumed by the template; the visual gate's pixel-diff probe simply did not observe a
    #       change under its specific test conditions (e.g. the probed value did not shift
    #       rendering, or the property is masked by focus/content state, as with PlaceholderText
    #       only rendering while the field is empty and unfocused). NOT silently ineffective.
    #
    #     'behavioral' - a known content/behavioral DP that the relevant WinUI BASE CLASS (TextBox
    #       for EtherInput, Control for EtherProgressBar) honors internally, independent of the
    #       ControlTemplate, so there is no TemplateBinding to find and no pixel-diff probe can
    #       observe it (it never exercises the behavior - typing, read-only enforcement, etc.).
    #       Functional, just not visually testable this way. NOT silently ineffective. Currently:
    #       EtherInput.AcceptsReturn/CharacterCasing/IsReadOnly, EtherProgressBar.IsEnabled.
    #
    #     'platform-noop' - a genuinely inert low-level DP with no TemplateBinding, no base-class
    #       behavior, and no consumer-visible effect expected (Clip, CompositeMode,
    #       BackgroundSizing - a rendering-detail DP, not a visual-identity choice like Background/
    #       BorderBrush/CornerRadius, so it does not belong in design-system-owned even though it
    #       is likewise unbound). Not something a consumer would reasonably expect to set.
    #
    #     'needs-review' - the TemplateBinding cross-check could not confidently resolve whether
    #       the property is behavioral (like AcceptsReturn/IsReadOnly) or genuinely dead (like a
    #       true design-system-owned entry), because unlike those confirmed cases there is no
    #       equally clear WinUI base-class precedent either way. Currently exactly 3:
    #       EtherInput.HorizontalTextAlignment, EtherDropdown.DisplayMemberPath,
    #       EtherDropdown.MaxDropDownHeight. Each carries a Reason describing the specific
    #       uncertainty and what a runtime probe would need to check to resolve it. Allowed to
    #       exist (a human has not decided yet); scripts/Verify-SilentPropertyCoverage.ps1 prints
    #       a loud WARNING listing them without failing, so they stay visible rather than buried.
    #
    #   TemplateBinding cross-check mechanism: the TemplateFiles hashtable at the bottom of this
    #   file maps each Control name appearing in AcknowledgedSilent to its ControlTemplate .xaml
    #   (the same file Entries above already reference per-entry). For every AcknowledgedSilent
    #   entry NOT in 'behavioral' or 'needs-review', scripts/Verify-SilentPropertyCoverage.ps1
    #   greps TemplateFiles[Control] for the literal token `{TemplateBinding <Property>}` - the
    #   exact same regex scripts/Verify-UnsupportedProperties.ps1 already uses for the 12 closed
    #   Entries (`\{TemplateBinding\s+<Property>\b`) - and FAILS the gate if the label disagrees
    #   with what the template file actually contains:
    #     - 'design-system-owned' but a TemplateBinding IS found -> FAIL (it is actually consumed;
    #       relabel it 'consumed-visually-stable')
    #     - 'consumed-visually-stable' but NO TemplateBinding is found -> FAIL (it is not actually
    #       consumed; relabel it 'design-system-owned' or 'platform-noop')
    #   This makes the classification self-verifying instead of merely asserted - a reviewer does
    #   not have to trust a human's read of the XAML, the gate re-derives it every run.
    #
    #   scripts/Verify-SilentPropertyCoverage.ps1 (a 'local-runtime' gate, since it needs the
    #   evidence file a GUI runtime pass produces) additionally enforces two directions against the
    #   newest evidence file:
    #     - forward: every platform-dp-contract property must be in Entries OR AcknowledgedSilent
    #       (a brand-new, unaccounted-for silently-ineffective property FAILS the gate, naming
    #       the property and asking a human to classify it - nothing is ever auto-added here)
    #     - reverse: every AcknowledgedSilent entry must STILL be platform-dp-contract in that
    #       evidence (so a property that becomes genuinely wired/observable cannot leave a stale,
    #       lying entry behind)
    #   This is the OPEN half of what was previously a closed, 12-entry-only detection mechanism.
    # ============================================================================================
    #
    # CheckKind:
    #   'TemplateBindingAbsent' - the property is a decoration-only DP (Header, HeaderTemplate,
    #     Description, PlaceholderText, PlaceholderForeground). WinUI's own default template
    #     renders these only via an explicit `{TemplateBinding <Property>}` somewhere in the
    #     ControlTemplate; there is no other mechanism. The gate asserts that exact token does
    #     not appear in TemplateFile.
    #   'TemplatePartAbsent' - the property only has an effect through a specific, framework-
    #     documented named template part (ComboBox's editable mode needs a part named
    #     "EditableText" - see [TemplatePart] on ComboBox). The gate asserts TemplateFile does
    #     not declare a part with that name.
    #
    # Empirical basis (see PR description / audit report for the full probe transcript): a
    # RegisterPropertyChangedCallback probe was attached to every property below on live
    # EtherDropdown / EtherInput / ToggleSwitch(EtherSwitch) instances and exercised through
    # construction, template application, selection change, dropdown open/close, focus,
    # IsEditable toggle + subsequent selection change, and IsOn toggle. Zero callbacks fired
    # for any of them except IsEditable itself firing once, synchronously, for the test's own
    # explicit write - confirming none of these DPs are written by WinUI internals during normal
    # interaction, so intercepting them carries no risk of collateral framework breakage.
    Entries = @(
        @{
            Control      = 'EtherDropdown'
            Property     = 'Header'
            BaseType     = 'ComboBox'
            TemplateFile = 'src/Ether.DesignSystem.Controls/Controls/Inputs/EtherDropdown.xaml'
            CheckKind    = 'TemplateBindingAbsent'
            Alternative  = 'Wrap the EtherDropdown in a StackPanel/Grid with an external TextBlock as the label, or use a form container that lays out its own label above the control.'
        }
        @{
            Control      = 'EtherDropdown'
            Property     = 'HeaderTemplate'
            BaseType     = 'ComboBox'
            TemplateFile = 'src/Ether.DesignSystem.Controls/Controls/Inputs/EtherDropdown.xaml'
            CheckKind    = 'TemplateBindingAbsent'
            Alternative  = 'Same as Header: build the label markup outside the control instead of via HeaderTemplate.'
        }
        @{
            Control      = 'EtherDropdown'
            Property     = 'Description'
            BaseType     = 'ComboBox'
            TemplateFile = 'src/Ether.DesignSystem.Controls/Controls/Inputs/EtherDropdown.xaml'
            CheckKind    = 'TemplateBindingAbsent'
            Alternative  = 'Place a second TextBlock below the control for helper/description text.'
        }
        @{
            Control      = 'EtherDropdown'
            Property     = 'PlaceholderText'
            BaseType     = 'ComboBox'
            TemplateFile = 'src/Ether.DesignSystem.Controls/Controls/Inputs/EtherDropdown.xaml'
            CheckKind    = 'TemplateBindingAbsent'
            Alternative  = 'EtherDropdown always shows a selected item via TriggerText; there is no unselected placeholder state. Add a real placeholder ComboBoxItem (e.g. Content="Select...") and treat it as the default selection instead.'
        }
        @{
            Control      = 'EtherDropdown'
            Property     = 'PlaceholderForeground'
            BaseType     = 'ComboBox'
            TemplateFile = 'src/Ether.DesignSystem.Controls/Controls/Inputs/EtherDropdown.xaml'
            CheckKind    = 'TemplateBindingAbsent'
            Alternative  = 'Follows PlaceholderText: not applicable while there is no placeholder visual.'
        }
        @{
            Control      = 'EtherDropdown'
            Property     = 'Text'
            BaseType     = 'ComboBox'
            TemplateFile = 'src/Ether.DesignSystem.Controls/Controls/Inputs/EtherDropdown.xaml'
            CheckKind    = 'TemplatePartAbsent'
            TemplatePartName = 'EditableText'
            Alternative  = 'EtherDropdown is a selection-only control (Figma spec has no free-text combo variant). It does not offer an editable mode. If consumers need free-text entry, use EtherInput, or a plain WinUI editable ComboBox styled separately.'
        }
        @{
            Control      = 'EtherDropdown'
            Property     = 'IsEditable'
            BaseType     = 'ComboBox'
            TemplateFile = 'src/Ether.DesignSystem.Controls/Controls/Inputs/EtherDropdown.xaml'
            CheckKind    = 'TemplatePartAbsent'
            TemplatePartName = 'EditableText'
            Alternative  = 'Same as Text: selection-only control by design, no editable mode. Setting IsEditable=true does not enable typing; it silently changes nothing because the template has no "EditableText" part.'
        }
        @{
            Control      = 'EtherInput'
            Property     = 'Header'
            BaseType     = 'TextBox'
            TemplateFile = 'src/Ether.DesignSystem.Controls/Controls/Inputs/EtherInput.xaml'
            CheckKind    = 'TemplateBindingAbsent'
            Alternative  = 'This is an existing, deliberate design decision (see the EtherInput.cs remarks: "does not add ... header/description slots"), not an oversight. Wrap EtherInput in your own label/description layout.'
        }
        @{
            Control      = 'EtherInput'
            Property     = 'HeaderTemplate'
            BaseType     = 'TextBox'
            TemplateFile = 'src/Ether.DesignSystem.Controls/Controls/Inputs/EtherInput.xaml'
            CheckKind    = 'TemplateBindingAbsent'
            Alternative  = 'Same as Header.'
        }
        @{
            Control      = 'EtherInput'
            Property     = 'Description'
            BaseType     = 'TextBox'
            TemplateFile = 'src/Ether.DesignSystem.Controls/Controls/Inputs/EtherInput.xaml'
            CheckKind    = 'TemplateBindingAbsent'
            Alternative  = 'Same as Header: place a second TextBlock below the control.'
        }
        @{
            Control      = 'EtherSwitch'
            Property     = 'Header'
            BaseType     = 'ToggleSwitch'
            TemplateFile = 'src/Ether.DesignSystem.Controls/Controls/Inputs/EtherSwitch.xaml'
            CheckKind    = 'TemplateBindingAbsent'
            Alternative  = 'EtherSwitch is a keyed Style="{StaticResource EtherSwitch}" applied to a stock ToggleSwitch, not a subclass; there is no code-behind to intercept the write in. Wrap the ToggleSwitch in your own label layout instead of using Header.'
        }
        @{
            Control      = 'EtherSwitch'
            Property     = 'HeaderTemplate'
            BaseType     = 'ToggleSwitch'
            TemplateFile = 'src/Ether.DesignSystem.Controls/Controls/Inputs/EtherSwitch.xaml'
            CheckKind    = 'TemplateBindingAbsent'
            Alternative  = 'Same as Header.'
        }
        # NOTE: ToggleSwitch does NOT have a Description property in Microsoft.WindowsAppSDK
        # 2.3.1 (confirmed via reflection: Microsoft.UI.Xaml.Controls.ToggleSwitch exposes only
        # Header and HeaderTemplate from this family - no Description). It was not added here.
    )

    # OPEN accounting (R-07) - see the file-header comment above for the full rule. Generated
    # programmatically from artifacts/audit-runs/consumer-runtime-evidence-20260831-033043851/
    # runtime-result.json's attachedVisualProperties.Evidence: every Method == 'platform-dp-
    # contract' property that is not already one of the 12 Entries above. 146 entries across 5
    # buckets - 94 design-system-owned + 30 platform-noop + 15 consumed-visually-stable + 4
    # behavioral + 3 needs-review (see the header comment for what each bucket means and the
    # TemplateBinding cross-check that makes 'design-system-owned' and 'consumed-visually-stable'
    # self-verifying against scripts/Verify-SilentPropertyCoverage.ps1). Do NOT hand-add entries
    # here for a newly-discovered platform-dp-contract property - regenerate from the newest
    # evidence file and re-apply the classification rule (or hand-classify a genuinely new/
    # ambiguous one as needs-review), so this list always traces back to a real evidence run
    # instead of accumulating hand-typed guesses.
    AcknowledgedSilent = @(
        # EtherButton
        @{ Property = 'EtherButton.BackgroundSizing'; Bucket = 'platform-noop'; Reason = 'Low-level rendering DP; not referenced via TemplateBinding in src/Ether.DesignSystem.Controls/Controls/Inputs/EtherButton.xaml, so no consumer value written to the control''s own BackgroundSizing property ever reaches rendering. Not part of the design system''s owned appearance surface and not something a consumer would reasonably expect to customize (unlike Background/BorderBrush/CornerRadius, which are visible identity choices).' }
        @{ Property = 'EtherButton.CharacterSpacing'; Bucket = 'design-system-owned'; Reason = 'Appearance property (Background/Border*/CornerRadius/Padding/Foreground/Font*/CharacterSpacing/*ContentAlignment family); no {TemplateBinding CharacterSpacing} in src/Ether.DesignSystem.Controls/Controls/Inputs/EtherButton.xaml - the design system deliberately does not let consumers override this to keep the visual language consistent across every app that consumes it (no visible effect is a FEATURE here, not a defect).' }
        @{ Property = 'EtherButton.CompositeMode'; Bucket = 'platform-noop'; Reason = 'Low-level UIElement rendering DP (CompositeMode) with no template consumption in src/Ether.DesignSystem.Controls/Controls/Inputs/EtherButton.xaml and no consumer-visible effect; not something a consumer would reasonably expect to set.' }
        @{ Property = 'EtherButton.FontStretch'; Bucket = 'design-system-owned'; Reason = 'Appearance property (Background/Border*/CornerRadius/Padding/Foreground/Font*/CharacterSpacing/*ContentAlignment family); no {TemplateBinding FontStretch} in src/Ether.DesignSystem.Controls/Controls/Inputs/EtherButton.xaml - the design system deliberately does not let consumers override this to keep the visual language consistent across every app that consumes it (no visible effect is a FEATURE here, not a defect).' }
        @{ Property = 'EtherButton.HorizontalContentAlignment'; Bucket = 'consumed-visually-stable'; Reason = '{TemplateBinding HorizontalContentAlignment} is present in src/Ether.DesignSystem.Controls/Controls/Inputs/EtherButton.xaml:216 - the property IS consumed by the template. The visual gate observed no pixel change under its test conditions; that reflects the probe''s conditions, not a lack of wiring. NOT silently ineffective.' }
        @{ Property = 'EtherButton.VerticalContentAlignment'; Bucket = 'consumed-visually-stable'; Reason = '{TemplateBinding VerticalContentAlignment} is present in src/Ether.DesignSystem.Controls/Controls/Inputs/EtherButton.xaml:217 - the property IS consumed by the template. The visual gate observed no pixel change under its test conditions; that reflects the probe''s conditions, not a lack of wiring. NOT silently ineffective.' }

        # EtherCheckbox
        @{ Property = 'EtherCheckbox.Background'; Bucket = 'design-system-owned'; Reason = 'Appearance property (Background/Border*/CornerRadius/Padding/Foreground/Font*/CharacterSpacing/*ContentAlignment family); no {TemplateBinding Background} in src/Ether.DesignSystem.Controls/Controls/Inputs/EtherCheckbox.xaml - the design system deliberately does not let consumers override this to keep the visual language consistent across every app that consumes it (no visible effect is a FEATURE here, not a defect).' }
        @{ Property = 'EtherCheckbox.BackgroundSizing'; Bucket = 'platform-noop'; Reason = 'Low-level rendering DP; not referenced via TemplateBinding in src/Ether.DesignSystem.Controls/Controls/Inputs/EtherCheckbox.xaml, so no consumer value written to the control''s own BackgroundSizing property ever reaches rendering. Not part of the design system''s owned appearance surface and not something a consumer would reasonably expect to customize (unlike Background/BorderBrush/CornerRadius, which are visible identity choices).' }
        @{ Property = 'EtherCheckbox.BorderBrush'; Bucket = 'design-system-owned'; Reason = 'Appearance property (Background/Border*/CornerRadius/Padding/Foreground/Font*/CharacterSpacing/*ContentAlignment family); no {TemplateBinding BorderBrush} in src/Ether.DesignSystem.Controls/Controls/Inputs/EtherCheckbox.xaml - the design system deliberately does not let consumers override this to keep the visual language consistent across every app that consumes it (no visible effect is a FEATURE here, not a defect).' }
        @{ Property = 'EtherCheckbox.BorderThickness'; Bucket = 'design-system-owned'; Reason = 'Appearance property (Background/Border*/CornerRadius/Padding/Foreground/Font*/CharacterSpacing/*ContentAlignment family); no {TemplateBinding BorderThickness} in src/Ether.DesignSystem.Controls/Controls/Inputs/EtherCheckbox.xaml - the design system deliberately does not let consumers override this to keep the visual language consistent across every app that consumes it (no visible effect is a FEATURE here, not a defect).' }
        @{ Property = 'EtherCheckbox.CharacterSpacing'; Bucket = 'design-system-owned'; Reason = 'Appearance property (Background/Border*/CornerRadius/Padding/Foreground/Font*/CharacterSpacing/*ContentAlignment family); no {TemplateBinding CharacterSpacing} in src/Ether.DesignSystem.Controls/Controls/Inputs/EtherCheckbox.xaml - the design system deliberately does not let consumers override this to keep the visual language consistent across every app that consumes it (no visible effect is a FEATURE here, not a defect).' }
        @{ Property = 'EtherCheckbox.Clip'; Bucket = 'platform-noop'; Reason = 'Low-level UIElement rendering DP (Clip) with no template consumption in src/Ether.DesignSystem.Controls/Controls/Inputs/EtherCheckbox.xaml and no consumer-visible effect; not something a consumer would reasonably expect to set.' }
        @{ Property = 'EtherCheckbox.CompositeMode'; Bucket = 'platform-noop'; Reason = 'Low-level UIElement rendering DP (CompositeMode) with no template consumption in src/Ether.DesignSystem.Controls/Controls/Inputs/EtherCheckbox.xaml and no consumer-visible effect; not something a consumer would reasonably expect to set.' }
        @{ Property = 'EtherCheckbox.CornerRadius'; Bucket = 'design-system-owned'; Reason = 'Appearance property (Background/Border*/CornerRadius/Padding/Foreground/Font*/CharacterSpacing/*ContentAlignment family); no {TemplateBinding CornerRadius} in src/Ether.DesignSystem.Controls/Controls/Inputs/EtherCheckbox.xaml - the design system deliberately does not let consumers override this to keep the visual language consistent across every app that consumes it (no visible effect is a FEATURE here, not a defect).' }
        @{ Property = 'EtherCheckbox.FontSize'; Bucket = 'design-system-owned'; Reason = 'Appearance property (Background/Border*/CornerRadius/Padding/Foreground/Font*/CharacterSpacing/*ContentAlignment family); no {TemplateBinding FontSize} in src/Ether.DesignSystem.Controls/Controls/Inputs/EtherCheckbox.xaml - the design system deliberately does not let consumers override this to keep the visual language consistent across every app that consumes it (no visible effect is a FEATURE here, not a defect).' }
        @{ Property = 'EtherCheckbox.FontStretch'; Bucket = 'design-system-owned'; Reason = 'Appearance property (Background/Border*/CornerRadius/Padding/Foreground/Font*/CharacterSpacing/*ContentAlignment family); no {TemplateBinding FontStretch} in src/Ether.DesignSystem.Controls/Controls/Inputs/EtherCheckbox.xaml - the design system deliberately does not let consumers override this to keep the visual language consistent across every app that consumes it (no visible effect is a FEATURE here, not a defect).' }
        @{ Property = 'EtherCheckbox.HorizontalContentAlignment'; Bucket = 'design-system-owned'; Reason = 'Appearance property (Background/Border*/CornerRadius/Padding/Foreground/Font*/CharacterSpacing/*ContentAlignment family); no {TemplateBinding HorizontalContentAlignment} in src/Ether.DesignSystem.Controls/Controls/Inputs/EtherCheckbox.xaml - the design system deliberately does not let consumers override this to keep the visual language consistent across every app that consumes it (no visible effect is a FEATURE here, not a defect).' }
        @{ Property = 'EtherCheckbox.Padding'; Bucket = 'design-system-owned'; Reason = 'Appearance property (Background/Border*/CornerRadius/Padding/Foreground/Font*/CharacterSpacing/*ContentAlignment family); no {TemplateBinding Padding} in src/Ether.DesignSystem.Controls/Controls/Inputs/EtherCheckbox.xaml - the design system deliberately does not let consumers override this to keep the visual language consistent across every app that consumes it (no visible effect is a FEATURE here, not a defect).' }
        @{ Property = 'EtherCheckbox.VerticalContentAlignment'; Bucket = 'design-system-owned'; Reason = 'Appearance property (Background/Border*/CornerRadius/Padding/Foreground/Font*/CharacterSpacing/*ContentAlignment family); no {TemplateBinding VerticalContentAlignment} in src/Ether.DesignSystem.Controls/Controls/Inputs/EtherCheckbox.xaml - the design system deliberately does not let consumers override this to keep the visual language consistent across every app that consumes it (no visible effect is a FEATURE here, not a defect).' }

        # EtherDropdown
        @{ Property = 'EtherDropdown.BackgroundSizing'; Bucket = 'platform-noop'; Reason = 'Low-level rendering DP; not referenced via TemplateBinding in src/Ether.DesignSystem.Controls/Controls/Inputs/EtherDropdown.xaml, so no consumer value written to the control''s own BackgroundSizing property ever reaches rendering. Not part of the design system''s owned appearance surface and not something a consumer would reasonably expect to customize (unlike Background/BorderBrush/CornerRadius, which are visible identity choices).' }
        @{ Property = 'EtherDropdown.BorderBrush'; Bucket = 'design-system-owned'; Reason = 'Appearance property (Background/Border*/CornerRadius/Padding/Foreground/Font*/CharacterSpacing/*ContentAlignment family); no {TemplateBinding BorderBrush} in src/Ether.DesignSystem.Controls/Controls/Inputs/EtherDropdown.xaml - the design system deliberately does not let consumers override this to keep the visual language consistent across every app that consumes it (no visible effect is a FEATURE here, not a defect).' }
        @{ Property = 'EtherDropdown.BorderThickness'; Bucket = 'design-system-owned'; Reason = 'Appearance property (Background/Border*/CornerRadius/Padding/Foreground/Font*/CharacterSpacing/*ContentAlignment family); no {TemplateBinding BorderThickness} in src/Ether.DesignSystem.Controls/Controls/Inputs/EtherDropdown.xaml - the design system deliberately does not let consumers override this to keep the visual language consistent across every app that consumes it (no visible effect is a FEATURE here, not a defect).' }
        @{ Property = 'EtherDropdown.CharacterSpacing'; Bucket = 'design-system-owned'; Reason = 'Appearance property (Background/Border*/CornerRadius/Padding/Foreground/Font*/CharacterSpacing/*ContentAlignment family); no {TemplateBinding CharacterSpacing} in src/Ether.DesignSystem.Controls/Controls/Inputs/EtherDropdown.xaml - the design system deliberately does not let consumers override this to keep the visual language consistent across every app that consumes it (no visible effect is a FEATURE here, not a defect).' }
        @{ Property = 'EtherDropdown.CompositeMode'; Bucket = 'platform-noop'; Reason = 'Low-level UIElement rendering DP (CompositeMode) with no template consumption in src/Ether.DesignSystem.Controls/Controls/Inputs/EtherDropdown.xaml and no consumer-visible effect; not something a consumer would reasonably expect to set.' }
        @{ Property = 'EtherDropdown.DisplayMemberPath'; Bucket = 'needs-review'; Reason = 'Uncertain: content-shaping DP for data-bound ComboBox item display. EtherDropdown''s template has no {TemplateBinding DisplayMemberPath} and the control is documented as selection-only (see the IsEditable trap Entry), which points toward platform-noop - but ComboBox''s own internal item-container generation may still consult this DP for non-ComboBoxItem bound data regardless of the outer ControlTemplate, the same way AcceptsReturn is honored without a TemplateBinding. Not confidently placed without a targeted runtime probe using a non-ComboBoxItem ItemsSource; flagged for human review rather than guessed.' }
        @{ Property = 'EtherDropdown.FontStretch'; Bucket = 'design-system-owned'; Reason = 'Appearance property (Background/Border*/CornerRadius/Padding/Foreground/Font*/CharacterSpacing/*ContentAlignment family); no {TemplateBinding FontStretch} in src/Ether.DesignSystem.Controls/Controls/Inputs/EtherDropdown.xaml - the design system deliberately does not let consumers override this to keep the visual language consistent across every app that consumes it (no visible effect is a FEATURE here, not a defect).' }
        @{ Property = 'EtherDropdown.HorizontalContentAlignment'; Bucket = 'consumed-visually-stable'; Reason = '{TemplateBinding HorizontalContentAlignment} is present in src/Ether.DesignSystem.Controls/Controls/Inputs/EtherDropdown.xaml:400 - the property IS consumed by the template. The visual gate observed no pixel change under its test conditions; that reflects the probe''s conditions, not a lack of wiring. NOT silently ineffective.' }
        @{ Property = 'EtherDropdown.MaxDropDownHeight'; Bucket = 'needs-review'; Reason = 'Uncertain: EtherDropdown''s Popup/PopupBorder/ScrollViewer parts appear to size the dropdown independently of this DP (no {TemplateBinding MaxDropDownHeight} in the template), pointing toward platform-noop - but ComboBox''s internal Popup-opening/placement logic may still clamp against this inherited value at a layer outside the named template parts, the way base-class behavior does for AcceptsReturn/IsReadOnly. Not confidently placed without a targeted runtime probe forcing the dropdown near screen-height limits; flagged for human review rather than guessed.' }
        @{ Property = 'EtherDropdown.VerticalContentAlignment'; Bucket = 'consumed-visually-stable'; Reason = '{TemplateBinding VerticalContentAlignment} is present in src/Ether.DesignSystem.Controls/Controls/Inputs/EtherDropdown.xaml:401 - the property IS consumed by the template. The visual gate observed no pixel change under its test conditions; that reflects the probe''s conditions, not a lack of wiring. NOT silently ineffective.' }

        # EtherInput
        @{ Property = 'EtherInput.AcceptsReturn'; Bucket = 'behavioral'; Reason = 'Behavioral, not appearance: WinUI''s base TextBox handles Enter-key/newline insertion into the text buffer internally, independent of the ControlTemplate - it only requires the named ContentElement/ScrollViewer part, which EtherInput''s template provides. Functional if a consumer sets it True; a static pixel-diff probe against an empty/unfocused control reports no visual change because it never exercises typing. NOT silently ineffective.' }
        @{ Property = 'EtherInput.BackgroundSizing'; Bucket = 'platform-noop'; Reason = 'Low-level rendering DP; not referenced via TemplateBinding in src/Ether.DesignSystem.Controls/Controls/Inputs/EtherInput.xaml, so no consumer value written to the control''s own BackgroundSizing property ever reaches rendering. Not part of the design system''s owned appearance surface and not something a consumer would reasonably expect to customize (unlike Background/BorderBrush/CornerRadius, which are visible identity choices).' }
        @{ Property = 'EtherInput.CharacterCasing'; Bucket = 'behavioral'; Reason = 'Behavioral, not appearance: WinUI''s base TextBox applies the upper/lower-case input transform to typed text internally, independent of the ControlTemplate. Functional; a static pixel-diff probe against unchanged text content cannot observe it because it never exercises typing. NOT silently ineffective.' }
        @{ Property = 'EtherInput.CompositeMode'; Bucket = 'platform-noop'; Reason = 'Low-level UIElement rendering DP (CompositeMode) with no template consumption in src/Ether.DesignSystem.Controls/Controls/Inputs/EtherInput.xaml and no consumer-visible effect; not something a consumer would reasonably expect to set.' }
        @{ Property = 'EtherInput.FontFamily'; Bucket = 'consumed-visually-stable'; Reason = '{TemplateBinding FontFamily} is present in src/Ether.DesignSystem.Controls/Controls/Inputs/EtherInput.xaml:153 - the property IS consumed by the template. The visual gate observed no pixel change under its test conditions; that reflects the probe''s conditions, not a lack of wiring. NOT silently ineffective.' }
        @{ Property = 'EtherInput.FontStretch'; Bucket = 'design-system-owned'; Reason = 'Appearance property (Background/Border*/CornerRadius/Padding/Foreground/Font*/CharacterSpacing/*ContentAlignment family); no {TemplateBinding FontStretch} in src/Ether.DesignSystem.Controls/Controls/Inputs/EtherInput.xaml - the design system deliberately does not let consumers override this to keep the visual language consistent across every app that consumes it (no visible effect is a FEATURE here, not a defect).' }
        @{ Property = 'EtherInput.HorizontalContentAlignment'; Bucket = 'design-system-owned'; Reason = 'Appearance property (Background/Border*/CornerRadius/Padding/Foreground/Font*/CharacterSpacing/*ContentAlignment family); no {TemplateBinding HorizontalContentAlignment} in src/Ether.DesignSystem.Controls/Controls/Inputs/EtherInput.xaml - the design system deliberately does not let consumers override this to keep the visual language consistent across every app that consumes it (no visible effect is a FEATURE here, not a defect).' }
        @{ Property = 'EtherInput.HorizontalTextAlignment'; Bucket = 'needs-review'; Reason = 'Uncertain: inherited TextBox DP with no {TemplateBinding HorizontalTextAlignment} in EtherInput.xaml, so the template itself does not visually consume it - but unlike AcceptsReturn/CharacterCasing/IsReadOnly (confirmed behavioral: base TextBox definitely applies those internally regardless of template), it is unclear whether WinUI''s internal TextBoxView honors this purely through base-class rendering (making it behavioral, like the other three) or whether it needs a template surface EtherInput''s custom Grid-based placeholder overlay does not provide (making it genuinely dead). Not confidently placed without a targeted runtime probe; flagged for human review rather than guessed.' }
        @{ Property = 'EtherInput.IsReadOnly'; Bucket = 'behavioral'; Reason = 'Behavioral, not appearance: WinUI''s base TextBox blocks keyboard/IME edits internally when set, independent of the ControlTemplate. Functional; the visual gate''s pixel-diff probe does not exercise typing, so it observes no change either way. NOT silently ineffective.' }
        @{ Property = 'EtherInput.PlaceholderForeground'; Bucket = 'consumed-visually-stable'; Reason = '{TemplateBinding PlaceholderForeground} is present in src/Ether.DesignSystem.Controls/Controls/Inputs/EtherInput.xaml:152 - the property IS consumed by the template. The visual gate observed no pixel change under its test conditions; that reflects the probe''s conditions, not a lack of wiring. NOT silently ineffective.' }
        @{ Property = 'EtherInput.PlaceholderText'; Bucket = 'consumed-visually-stable'; Reason = '{TemplateBinding PlaceholderText} is present in src/Ether.DesignSystem.Controls/Controls/Inputs/EtherInput.xaml:150 - the property IS consumed by the template. The visual gate observed no pixel change under its test conditions; that reflects the probe''s conditions, not a lack of wiring. NOT silently ineffective.' }
        @{ Property = 'EtherInput.VerticalContentAlignment'; Bucket = 'design-system-owned'; Reason = 'Appearance property (Background/Border*/CornerRadius/Padding/Foreground/Font*/CharacterSpacing/*ContentAlignment family); no {TemplateBinding VerticalContentAlignment} in src/Ether.DesignSystem.Controls/Controls/Inputs/EtherInput.xaml - the design system deliberately does not let consumers override this to keep the visual language consistent across every app that consumes it (no visible effect is a FEATURE here, not a defect).' }

        # EtherIntelligenceButton
        @{ Property = 'EtherIntelligenceButton.Background'; Bucket = 'design-system-owned'; Reason = 'Appearance property (Background/Border*/CornerRadius/Padding/Foreground/Font*/CharacterSpacing/*ContentAlignment family); no {TemplateBinding Background} in src/Ether.DesignSystem.Controls/Controls/Inputs/EtherIntelligenceButton.xaml - the design system deliberately does not let consumers override this to keep the visual language consistent across every app that consumes it (no visible effect is a FEATURE here, not a defect).' }
        @{ Property = 'EtherIntelligenceButton.BackgroundSizing'; Bucket = 'platform-noop'; Reason = 'Low-level rendering DP; not referenced via TemplateBinding in src/Ether.DesignSystem.Controls/Controls/Inputs/EtherIntelligenceButton.xaml, so no consumer value written to the control''s own BackgroundSizing property ever reaches rendering. Not part of the design system''s owned appearance surface and not something a consumer would reasonably expect to customize (unlike Background/BorderBrush/CornerRadius, which are visible identity choices).' }
        @{ Property = 'EtherIntelligenceButton.BorderBrush'; Bucket = 'design-system-owned'; Reason = 'Appearance property (Background/Border*/CornerRadius/Padding/Foreground/Font*/CharacterSpacing/*ContentAlignment family); no {TemplateBinding BorderBrush} in src/Ether.DesignSystem.Controls/Controls/Inputs/EtherIntelligenceButton.xaml - the design system deliberately does not let consumers override this to keep the visual language consistent across every app that consumes it (no visible effect is a FEATURE here, not a defect).' }
        @{ Property = 'EtherIntelligenceButton.BorderThickness'; Bucket = 'design-system-owned'; Reason = 'Appearance property (Background/Border*/CornerRadius/Padding/Foreground/Font*/CharacterSpacing/*ContentAlignment family); no {TemplateBinding BorderThickness} in src/Ether.DesignSystem.Controls/Controls/Inputs/EtherIntelligenceButton.xaml - the design system deliberately does not let consumers override this to keep the visual language consistent across every app that consumes it (no visible effect is a FEATURE here, not a defect).' }
        @{ Property = 'EtherIntelligenceButton.CharacterSpacing'; Bucket = 'design-system-owned'; Reason = 'Appearance property (Background/Border*/CornerRadius/Padding/Foreground/Font*/CharacterSpacing/*ContentAlignment family); no {TemplateBinding CharacterSpacing} in src/Ether.DesignSystem.Controls/Controls/Inputs/EtherIntelligenceButton.xaml - the design system deliberately does not let consumers override this to keep the visual language consistent across every app that consumes it (no visible effect is a FEATURE here, not a defect).' }
        @{ Property = 'EtherIntelligenceButton.CompositeMode'; Bucket = 'platform-noop'; Reason = 'Low-level UIElement rendering DP (CompositeMode) with no template consumption in src/Ether.DesignSystem.Controls/Controls/Inputs/EtherIntelligenceButton.xaml and no consumer-visible effect; not something a consumer would reasonably expect to set.' }
        @{ Property = 'EtherIntelligenceButton.CornerRadius'; Bucket = 'design-system-owned'; Reason = 'Appearance property (Background/Border*/CornerRadius/Padding/Foreground/Font*/CharacterSpacing/*ContentAlignment family); no {TemplateBinding CornerRadius} in src/Ether.DesignSystem.Controls/Controls/Inputs/EtherIntelligenceButton.xaml - the design system deliberately does not let consumers override this to keep the visual language consistent across every app that consumes it (no visible effect is a FEATURE here, not a defect).' }
        @{ Property = 'EtherIntelligenceButton.FontFamily'; Bucket = 'design-system-owned'; Reason = 'Appearance property (Background/Border*/CornerRadius/Padding/Foreground/Font*/CharacterSpacing/*ContentAlignment family); no {TemplateBinding FontFamily} in src/Ether.DesignSystem.Controls/Controls/Inputs/EtherIntelligenceButton.xaml - the design system deliberately does not let consumers override this to keep the visual language consistent across every app that consumes it (no visible effect is a FEATURE here, not a defect).' }
        @{ Property = 'EtherIntelligenceButton.FontSize'; Bucket = 'design-system-owned'; Reason = 'Appearance property (Background/Border*/CornerRadius/Padding/Foreground/Font*/CharacterSpacing/*ContentAlignment family); no {TemplateBinding FontSize} in src/Ether.DesignSystem.Controls/Controls/Inputs/EtherIntelligenceButton.xaml - the design system deliberately does not let consumers override this to keep the visual language consistent across every app that consumes it (no visible effect is a FEATURE here, not a defect).' }
        @{ Property = 'EtherIntelligenceButton.FontStretch'; Bucket = 'design-system-owned'; Reason = 'Appearance property (Background/Border*/CornerRadius/Padding/Foreground/Font*/CharacterSpacing/*ContentAlignment family); no {TemplateBinding FontStretch} in src/Ether.DesignSystem.Controls/Controls/Inputs/EtherIntelligenceButton.xaml - the design system deliberately does not let consumers override this to keep the visual language consistent across every app that consumes it (no visible effect is a FEATURE here, not a defect).' }
        @{ Property = 'EtherIntelligenceButton.FontWeight'; Bucket = 'design-system-owned'; Reason = 'Appearance property (Background/Border*/CornerRadius/Padding/Foreground/Font*/CharacterSpacing/*ContentAlignment family); no {TemplateBinding FontWeight} in src/Ether.DesignSystem.Controls/Controls/Inputs/EtherIntelligenceButton.xaml - the design system deliberately does not let consumers override this to keep the visual language consistent across every app that consumes it (no visible effect is a FEATURE here, not a defect).' }
        @{ Property = 'EtherIntelligenceButton.Foreground'; Bucket = 'design-system-owned'; Reason = 'Appearance property (Background/Border*/CornerRadius/Padding/Foreground/Font*/CharacterSpacing/*ContentAlignment family); no {TemplateBinding Foreground} in src/Ether.DesignSystem.Controls/Controls/Inputs/EtherIntelligenceButton.xaml - the design system deliberately does not let consumers override this to keep the visual language consistent across every app that consumes it (no visible effect is a FEATURE here, not a defect).' }
        @{ Property = 'EtherIntelligenceButton.HorizontalContentAlignment'; Bucket = 'consumed-visually-stable'; Reason = '{TemplateBinding HorizontalContentAlignment} is present in src/Ether.DesignSystem.Controls/Controls/Inputs/EtherIntelligenceButton.xaml:208 - the property IS consumed by the template. The visual gate observed no pixel change under its test conditions; that reflects the probe''s conditions, not a lack of wiring. NOT silently ineffective.' }
        @{ Property = 'EtherIntelligenceButton.VerticalContentAlignment'; Bucket = 'consumed-visually-stable'; Reason = '{TemplateBinding VerticalContentAlignment} is present in src/Ether.DesignSystem.Controls/Controls/Inputs/EtherIntelligenceButton.xaml:209 - the property IS consumed by the template. The visual gate observed no pixel change under its test conditions; that reflects the probe''s conditions, not a lack of wiring. NOT silently ineffective.' }

        # EtherMasthead
        @{ Property = 'EtherMasthead.BackgroundSizing'; Bucket = 'platform-noop'; Reason = 'Low-level rendering DP; not referenced via TemplateBinding in src/Ether.DesignSystem.Controls/Controls/Navigation/EtherMasthead.xaml, so no consumer value written to the control''s own BackgroundSizing property ever reaches rendering. Not part of the design system''s owned appearance surface and not something a consumer would reasonably expect to customize (unlike Background/BorderBrush/CornerRadius, which are visible identity choices).' }
        @{ Property = 'EtherMasthead.BorderBrush'; Bucket = 'consumed-visually-stable'; Reason = '{TemplateBinding BorderBrush} is present in src/Ether.DesignSystem.Controls/Controls/Navigation/EtherMasthead.xaml:108 - the property IS consumed by the template. The visual gate observed no pixel change under its test conditions; that reflects the probe''s conditions, not a lack of wiring. NOT silently ineffective.' }
        @{ Property = 'EtherMasthead.BorderThickness'; Bucket = 'consumed-visually-stable'; Reason = '{TemplateBinding BorderThickness} is present in src/Ether.DesignSystem.Controls/Controls/Navigation/EtherMasthead.xaml:109 - the property IS consumed by the template. The visual gate observed no pixel change under its test conditions; that reflects the probe''s conditions, not a lack of wiring. NOT silently ineffective.' }
        @{ Property = 'EtherMasthead.CharacterSpacing'; Bucket = 'design-system-owned'; Reason = 'Appearance property (Background/Border*/CornerRadius/Padding/Foreground/Font*/CharacterSpacing/*ContentAlignment family); no {TemplateBinding CharacterSpacing} in src/Ether.DesignSystem.Controls/Controls/Navigation/EtherMasthead.xaml - the design system deliberately does not let consumers override this to keep the visual language consistent across every app that consumes it (no visible effect is a FEATURE here, not a defect).' }
        @{ Property = 'EtherMasthead.Clip'; Bucket = 'platform-noop'; Reason = 'Low-level UIElement rendering DP (Clip) with no template consumption in src/Ether.DesignSystem.Controls/Controls/Navigation/EtherMasthead.xaml and no consumer-visible effect; not something a consumer would reasonably expect to set.' }
        @{ Property = 'EtherMasthead.CompositeMode'; Bucket = 'platform-noop'; Reason = 'Low-level UIElement rendering DP (CompositeMode) with no template consumption in src/Ether.DesignSystem.Controls/Controls/Navigation/EtherMasthead.xaml and no consumer-visible effect; not something a consumer would reasonably expect to set.' }
        @{ Property = 'EtherMasthead.CornerRadius'; Bucket = 'design-system-owned'; Reason = 'Appearance property (Background/Border*/CornerRadius/Padding/Foreground/Font*/CharacterSpacing/*ContentAlignment family); no {TemplateBinding CornerRadius} in src/Ether.DesignSystem.Controls/Controls/Navigation/EtherMasthead.xaml - the design system deliberately does not let consumers override this to keep the visual language consistent across every app that consumes it (no visible effect is a FEATURE here, not a defect).' }
        @{ Property = 'EtherMasthead.FontFamily'; Bucket = 'design-system-owned'; Reason = 'Appearance property (Background/Border*/CornerRadius/Padding/Foreground/Font*/CharacterSpacing/*ContentAlignment family); no {TemplateBinding FontFamily} in src/Ether.DesignSystem.Controls/Controls/Navigation/EtherMasthead.xaml - the design system deliberately does not let consumers override this to keep the visual language consistent across every app that consumes it (no visible effect is a FEATURE here, not a defect).' }
        @{ Property = 'EtherMasthead.FontSize'; Bucket = 'design-system-owned'; Reason = 'Appearance property (Background/Border*/CornerRadius/Padding/Foreground/Font*/CharacterSpacing/*ContentAlignment family); no {TemplateBinding FontSize} in src/Ether.DesignSystem.Controls/Controls/Navigation/EtherMasthead.xaml - the design system deliberately does not let consumers override this to keep the visual language consistent across every app that consumes it (no visible effect is a FEATURE here, not a defect).' }
        @{ Property = 'EtherMasthead.FontStretch'; Bucket = 'design-system-owned'; Reason = 'Appearance property (Background/Border*/CornerRadius/Padding/Foreground/Font*/CharacterSpacing/*ContentAlignment family); no {TemplateBinding FontStretch} in src/Ether.DesignSystem.Controls/Controls/Navigation/EtherMasthead.xaml - the design system deliberately does not let consumers override this to keep the visual language consistent across every app that consumes it (no visible effect is a FEATURE here, not a defect).' }
        @{ Property = 'EtherMasthead.FontStyle'; Bucket = 'design-system-owned'; Reason = 'Appearance property (Background/Border*/CornerRadius/Padding/Foreground/Font*/CharacterSpacing/*ContentAlignment family); no {TemplateBinding FontStyle} in src/Ether.DesignSystem.Controls/Controls/Navigation/EtherMasthead.xaml - the design system deliberately does not let consumers override this to keep the visual language consistent across every app that consumes it (no visible effect is a FEATURE here, not a defect).' }
        @{ Property = 'EtherMasthead.FontWeight'; Bucket = 'design-system-owned'; Reason = 'Appearance property (Background/Border*/CornerRadius/Padding/Foreground/Font*/CharacterSpacing/*ContentAlignment family); no {TemplateBinding FontWeight} in src/Ether.DesignSystem.Controls/Controls/Navigation/EtherMasthead.xaml - the design system deliberately does not let consumers override this to keep the visual language consistent across every app that consumes it (no visible effect is a FEATURE here, not a defect).' }
        @{ Property = 'EtherMasthead.Foreground'; Bucket = 'design-system-owned'; Reason = 'Appearance property (Background/Border*/CornerRadius/Padding/Foreground/Font*/CharacterSpacing/*ContentAlignment family); no {TemplateBinding Foreground} in src/Ether.DesignSystem.Controls/Controls/Navigation/EtherMasthead.xaml - the design system deliberately does not let consumers override this to keep the visual language consistent across every app that consumes it (no visible effect is a FEATURE here, not a defect).' }
        @{ Property = 'EtherMasthead.HorizontalContentAlignment'; Bucket = 'design-system-owned'; Reason = 'Appearance property (Background/Border*/CornerRadius/Padding/Foreground/Font*/CharacterSpacing/*ContentAlignment family); no {TemplateBinding HorizontalContentAlignment} in src/Ether.DesignSystem.Controls/Controls/Navigation/EtherMasthead.xaml - the design system deliberately does not let consumers override this to keep the visual language consistent across every app that consumes it (no visible effect is a FEATURE here, not a defect).' }
        @{ Property = 'EtherMasthead.Padding'; Bucket = 'design-system-owned'; Reason = 'Appearance property (Background/Border*/CornerRadius/Padding/Foreground/Font*/CharacterSpacing/*ContentAlignment family); no {TemplateBinding Padding} in src/Ether.DesignSystem.Controls/Controls/Navigation/EtherMasthead.xaml - the design system deliberately does not let consumers override this to keep the visual language consistent across every app that consumes it (no visible effect is a FEATURE here, not a defect).' }
        @{ Property = 'EtherMasthead.VerticalContentAlignment'; Bucket = 'design-system-owned'; Reason = 'Appearance property (Background/Border*/CornerRadius/Padding/Foreground/Font*/CharacterSpacing/*ContentAlignment family); no {TemplateBinding VerticalContentAlignment} in src/Ether.DesignSystem.Controls/Controls/Navigation/EtherMasthead.xaml - the design system deliberately does not let consumers override this to keep the visual language consistent across every app that consumes it (no visible effect is a FEATURE here, not a defect).' }

        # EtherProgressBar
        @{ Property = 'EtherProgressBar.Background'; Bucket = 'design-system-owned'; Reason = 'Appearance property (Background/Border*/CornerRadius/Padding/Foreground/Font*/CharacterSpacing/*ContentAlignment family); no {TemplateBinding Background} in src/Ether.DesignSystem.Controls/Controls/Inputs/EtherProgressBar.xaml - the design system deliberately does not let consumers override this to keep the visual language consistent across every app that consumes it (no visible effect is a FEATURE here, not a defect).' }
        @{ Property = 'EtherProgressBar.BackgroundSizing'; Bucket = 'platform-noop'; Reason = 'Low-level rendering DP; not referenced via TemplateBinding in src/Ether.DesignSystem.Controls/Controls/Inputs/EtherProgressBar.xaml, so no consumer value written to the control''s own BackgroundSizing property ever reaches rendering. Not part of the design system''s owned appearance surface and not something a consumer would reasonably expect to customize (unlike Background/BorderBrush/CornerRadius, which are visible identity choices).' }
        @{ Property = 'EtherProgressBar.BorderBrush'; Bucket = 'design-system-owned'; Reason = 'Appearance property (Background/Border*/CornerRadius/Padding/Foreground/Font*/CharacterSpacing/*ContentAlignment family); no {TemplateBinding BorderBrush} in src/Ether.DesignSystem.Controls/Controls/Inputs/EtherProgressBar.xaml - the design system deliberately does not let consumers override this to keep the visual language consistent across every app that consumes it (no visible effect is a FEATURE here, not a defect).' }
        @{ Property = 'EtherProgressBar.BorderThickness'; Bucket = 'design-system-owned'; Reason = 'Appearance property (Background/Border*/CornerRadius/Padding/Foreground/Font*/CharacterSpacing/*ContentAlignment family); no {TemplateBinding BorderThickness} in src/Ether.DesignSystem.Controls/Controls/Inputs/EtherProgressBar.xaml - the design system deliberately does not let consumers override this to keep the visual language consistent across every app that consumes it (no visible effect is a FEATURE here, not a defect).' }
        @{ Property = 'EtherProgressBar.CharacterSpacing'; Bucket = 'design-system-owned'; Reason = 'Appearance property (Background/Border*/CornerRadius/Padding/Foreground/Font*/CharacterSpacing/*ContentAlignment family); no {TemplateBinding CharacterSpacing} in src/Ether.DesignSystem.Controls/Controls/Inputs/EtherProgressBar.xaml - the design system deliberately does not let consumers override this to keep the visual language consistent across every app that consumes it (no visible effect is a FEATURE here, not a defect).' }
        @{ Property = 'EtherProgressBar.Clip'; Bucket = 'platform-noop'; Reason = 'Low-level UIElement rendering DP (Clip) with no template consumption in src/Ether.DesignSystem.Controls/Controls/Inputs/EtherProgressBar.xaml and no consumer-visible effect; not something a consumer would reasonably expect to set.' }
        @{ Property = 'EtherProgressBar.CompositeMode'; Bucket = 'platform-noop'; Reason = 'Low-level UIElement rendering DP (CompositeMode) with no template consumption in src/Ether.DesignSystem.Controls/Controls/Inputs/EtherProgressBar.xaml and no consumer-visible effect; not something a consumer would reasonably expect to set.' }
        @{ Property = 'EtherProgressBar.CornerRadius'; Bucket = 'design-system-owned'; Reason = 'Appearance property (Background/Border*/CornerRadius/Padding/Foreground/Font*/CharacterSpacing/*ContentAlignment family); no {TemplateBinding CornerRadius} in src/Ether.DesignSystem.Controls/Controls/Inputs/EtherProgressBar.xaml - the design system deliberately does not let consumers override this to keep the visual language consistent across every app that consumes it (no visible effect is a FEATURE here, not a defect).' }
        @{ Property = 'EtherProgressBar.FontFamily'; Bucket = 'design-system-owned'; Reason = 'Appearance property (Background/Border*/CornerRadius/Padding/Foreground/Font*/CharacterSpacing/*ContentAlignment family); no {TemplateBinding FontFamily} in src/Ether.DesignSystem.Controls/Controls/Inputs/EtherProgressBar.xaml - the design system deliberately does not let consumers override this to keep the visual language consistent across every app that consumes it (no visible effect is a FEATURE here, not a defect).' }
        @{ Property = 'EtherProgressBar.FontSize'; Bucket = 'design-system-owned'; Reason = 'Appearance property (Background/Border*/CornerRadius/Padding/Foreground/Font*/CharacterSpacing/*ContentAlignment family); no {TemplateBinding FontSize} in src/Ether.DesignSystem.Controls/Controls/Inputs/EtherProgressBar.xaml - the design system deliberately does not let consumers override this to keep the visual language consistent across every app that consumes it (no visible effect is a FEATURE here, not a defect).' }
        @{ Property = 'EtherProgressBar.FontStretch'; Bucket = 'design-system-owned'; Reason = 'Appearance property (Background/Border*/CornerRadius/Padding/Foreground/Font*/CharacterSpacing/*ContentAlignment family); no {TemplateBinding FontStretch} in src/Ether.DesignSystem.Controls/Controls/Inputs/EtherProgressBar.xaml - the design system deliberately does not let consumers override this to keep the visual language consistent across every app that consumes it (no visible effect is a FEATURE here, not a defect).' }
        @{ Property = 'EtherProgressBar.FontStyle'; Bucket = 'design-system-owned'; Reason = 'Appearance property (Background/Border*/CornerRadius/Padding/Foreground/Font*/CharacterSpacing/*ContentAlignment family); no {TemplateBinding FontStyle} in src/Ether.DesignSystem.Controls/Controls/Inputs/EtherProgressBar.xaml - the design system deliberately does not let consumers override this to keep the visual language consistent across every app that consumes it (no visible effect is a FEATURE here, not a defect).' }
        @{ Property = 'EtherProgressBar.FontWeight'; Bucket = 'design-system-owned'; Reason = 'Appearance property (Background/Border*/CornerRadius/Padding/Foreground/Font*/CharacterSpacing/*ContentAlignment family); no {TemplateBinding FontWeight} in src/Ether.DesignSystem.Controls/Controls/Inputs/EtherProgressBar.xaml - the design system deliberately does not let consumers override this to keep the visual language consistent across every app that consumes it (no visible effect is a FEATURE here, not a defect).' }
        @{ Property = 'EtherProgressBar.Foreground'; Bucket = 'design-system-owned'; Reason = 'Appearance property (Background/Border*/CornerRadius/Padding/Foreground/Font*/CharacterSpacing/*ContentAlignment family); no {TemplateBinding Foreground} in src/Ether.DesignSystem.Controls/Controls/Inputs/EtherProgressBar.xaml - the design system deliberately does not let consumers override this to keep the visual language consistent across every app that consumes it (no visible effect is a FEATURE here, not a defect).' }
        @{ Property = 'EtherProgressBar.HorizontalContentAlignment'; Bucket = 'design-system-owned'; Reason = 'Appearance property (Background/Border*/CornerRadius/Padding/Foreground/Font*/CharacterSpacing/*ContentAlignment family); no {TemplateBinding HorizontalContentAlignment} in src/Ether.DesignSystem.Controls/Controls/Inputs/EtherProgressBar.xaml - the design system deliberately does not let consumers override this to keep the visual language consistent across every app that consumes it (no visible effect is a FEATURE here, not a defect).' }
        @{ Property = 'EtherProgressBar.IsEnabled'; Bucket = 'behavioral'; Reason = 'Behavioral, inherited from Control: WinUI applies base disabled-state input/automation handling (hit-test/focus/AutomationProperties) independent of the ControlTemplate''s VisualStateManager wiring. EtherProgressBar''s visual states have no Disabled trigger, so the RENDERED APPEARANCE is identical enabled or disabled (which is what the pixel-diff probe sees) - but the interactive/automation state still changes. Practical consumer impact is small (progress bars are not pointer-interactive to begin with), so this is low-stakes, but it is not accurate to call it silently ineffective.' }
        @{ Property = 'EtherProgressBar.VerticalContentAlignment'; Bucket = 'design-system-owned'; Reason = 'Appearance property (Background/Border*/CornerRadius/Padding/Foreground/Font*/CharacterSpacing/*ContentAlignment family); no {TemplateBinding VerticalContentAlignment} in src/Ether.DesignSystem.Controls/Controls/Inputs/EtherProgressBar.xaml - the design system deliberately does not let consumers override this to keep the visual language consistent across every app that consumes it (no visible effect is a FEATURE here, not a defect).' }

        # EtherRadioButton
        @{ Property = 'EtherRadioButton.Background'; Bucket = 'design-system-owned'; Reason = 'Appearance property (Background/Border*/CornerRadius/Padding/Foreground/Font*/CharacterSpacing/*ContentAlignment family); no {TemplateBinding Background} in src/Ether.DesignSystem.Controls/Controls/Inputs/EtherRadioButton.xaml - the design system deliberately does not let consumers override this to keep the visual language consistent across every app that consumes it (no visible effect is a FEATURE here, not a defect).' }
        @{ Property = 'EtherRadioButton.BackgroundSizing'; Bucket = 'platform-noop'; Reason = 'Low-level rendering DP; not referenced via TemplateBinding in src/Ether.DesignSystem.Controls/Controls/Inputs/EtherRadioButton.xaml, so no consumer value written to the control''s own BackgroundSizing property ever reaches rendering. Not part of the design system''s owned appearance surface and not something a consumer would reasonably expect to customize (unlike Background/BorderBrush/CornerRadius, which are visible identity choices).' }
        @{ Property = 'EtherRadioButton.BorderBrush'; Bucket = 'design-system-owned'; Reason = 'Appearance property (Background/Border*/CornerRadius/Padding/Foreground/Font*/CharacterSpacing/*ContentAlignment family); no {TemplateBinding BorderBrush} in src/Ether.DesignSystem.Controls/Controls/Inputs/EtherRadioButton.xaml - the design system deliberately does not let consumers override this to keep the visual language consistent across every app that consumes it (no visible effect is a FEATURE here, not a defect).' }
        @{ Property = 'EtherRadioButton.BorderThickness'; Bucket = 'design-system-owned'; Reason = 'Appearance property (Background/Border*/CornerRadius/Padding/Foreground/Font*/CharacterSpacing/*ContentAlignment family); no {TemplateBinding BorderThickness} in src/Ether.DesignSystem.Controls/Controls/Inputs/EtherRadioButton.xaml - the design system deliberately does not let consumers override this to keep the visual language consistent across every app that consumes it (no visible effect is a FEATURE here, not a defect).' }
        @{ Property = 'EtherRadioButton.CharacterSpacing'; Bucket = 'design-system-owned'; Reason = 'Appearance property (Background/Border*/CornerRadius/Padding/Foreground/Font*/CharacterSpacing/*ContentAlignment family); no {TemplateBinding CharacterSpacing} in src/Ether.DesignSystem.Controls/Controls/Inputs/EtherRadioButton.xaml - the design system deliberately does not let consumers override this to keep the visual language consistent across every app that consumes it (no visible effect is a FEATURE here, not a defect).' }
        @{ Property = 'EtherRadioButton.Clip'; Bucket = 'platform-noop'; Reason = 'Low-level UIElement rendering DP (Clip) with no template consumption in src/Ether.DesignSystem.Controls/Controls/Inputs/EtherRadioButton.xaml and no consumer-visible effect; not something a consumer would reasonably expect to set.' }
        @{ Property = 'EtherRadioButton.CompositeMode'; Bucket = 'platform-noop'; Reason = 'Low-level UIElement rendering DP (CompositeMode) with no template consumption in src/Ether.DesignSystem.Controls/Controls/Inputs/EtherRadioButton.xaml and no consumer-visible effect; not something a consumer would reasonably expect to set.' }
        @{ Property = 'EtherRadioButton.CornerRadius'; Bucket = 'design-system-owned'; Reason = 'Appearance property (Background/Border*/CornerRadius/Padding/Foreground/Font*/CharacterSpacing/*ContentAlignment family); no {TemplateBinding CornerRadius} in src/Ether.DesignSystem.Controls/Controls/Inputs/EtherRadioButton.xaml - the design system deliberately does not let consumers override this to keep the visual language consistent across every app that consumes it (no visible effect is a FEATURE here, not a defect).' }
        @{ Property = 'EtherRadioButton.FontSize'; Bucket = 'design-system-owned'; Reason = 'Appearance property (Background/Border*/CornerRadius/Padding/Foreground/Font*/CharacterSpacing/*ContentAlignment family); no {TemplateBinding FontSize} in src/Ether.DesignSystem.Controls/Controls/Inputs/EtherRadioButton.xaml - the design system deliberately does not let consumers override this to keep the visual language consistent across every app that consumes it (no visible effect is a FEATURE here, not a defect).' }
        @{ Property = 'EtherRadioButton.FontStretch'; Bucket = 'design-system-owned'; Reason = 'Appearance property (Background/Border*/CornerRadius/Padding/Foreground/Font*/CharacterSpacing/*ContentAlignment family); no {TemplateBinding FontStretch} in src/Ether.DesignSystem.Controls/Controls/Inputs/EtherRadioButton.xaml - the design system deliberately does not let consumers override this to keep the visual language consistent across every app that consumes it (no visible effect is a FEATURE here, not a defect).' }
        @{ Property = 'EtherRadioButton.HorizontalContentAlignment'; Bucket = 'design-system-owned'; Reason = 'Appearance property (Background/Border*/CornerRadius/Padding/Foreground/Font*/CharacterSpacing/*ContentAlignment family); no {TemplateBinding HorizontalContentAlignment} in src/Ether.DesignSystem.Controls/Controls/Inputs/EtherRadioButton.xaml - the design system deliberately does not let consumers override this to keep the visual language consistent across every app that consumes it (no visible effect is a FEATURE here, not a defect).' }
        @{ Property = 'EtherRadioButton.Padding'; Bucket = 'design-system-owned'; Reason = 'Appearance property (Background/Border*/CornerRadius/Padding/Foreground/Font*/CharacterSpacing/*ContentAlignment family); no {TemplateBinding Padding} in src/Ether.DesignSystem.Controls/Controls/Inputs/EtherRadioButton.xaml - the design system deliberately does not let consumers override this to keep the visual language consistent across every app that consumes it (no visible effect is a FEATURE here, not a defect).' }
        @{ Property = 'EtherRadioButton.VerticalContentAlignment'; Bucket = 'design-system-owned'; Reason = 'Appearance property (Background/Border*/CornerRadius/Padding/Foreground/Font*/CharacterSpacing/*ContentAlignment family); no {TemplateBinding VerticalContentAlignment} in src/Ether.DesignSystem.Controls/Controls/Inputs/EtherRadioButton.xaml - the design system deliberately does not let consumers override this to keep the visual language consistent across every app that consumes it (no visible effect is a FEATURE here, not a defect).' }

        # EtherSegmentPanel
        @{ Property = 'EtherSegmentPanel.Clip'; Bucket = 'platform-noop'; Reason = 'EtherSegmentPanel is a Panel (FrameworkElement subclass), not a templated Control - there is no ControlTemplate/TemplateBinding concept for it. Clip is a low-level UIElement rendering DP with no consumer-visible effect; not something a consumer would reasonably expect to set on a Panel.' }
        @{ Property = 'EtherSegmentPanel.CompositeMode'; Bucket = 'platform-noop'; Reason = 'EtherSegmentPanel is a Panel (FrameworkElement subclass), not a templated Control - there is no ControlTemplate/TemplateBinding concept for it. CompositeMode is a low-level UIElement rendering DP with no consumer-visible effect; not something a consumer would reasonably expect to set on a Panel.' }

        # EtherSegmentedControl
        @{ Property = 'EtherSegmentedControl.BackgroundSizing'; Bucket = 'platform-noop'; Reason = 'Low-level rendering DP; not referenced via TemplateBinding in src/Ether.DesignSystem.Controls/Controls/Inputs/EtherSegmentedControl.xaml, so no consumer value written to the control''s own BackgroundSizing property ever reaches rendering. Not part of the design system''s owned appearance surface and not something a consumer would reasonably expect to customize (unlike Background/BorderBrush/CornerRadius, which are visible identity choices).' }
        @{ Property = 'EtherSegmentedControl.BorderBrush'; Bucket = 'design-system-owned'; Reason = 'Appearance property (Background/Border*/CornerRadius/Padding/Foreground/Font*/CharacterSpacing/*ContentAlignment family); no {TemplateBinding BorderBrush} in src/Ether.DesignSystem.Controls/Controls/Inputs/EtherSegmentedControl.xaml - the design system deliberately does not let consumers override this to keep the visual language consistent across every app that consumes it (no visible effect is a FEATURE here, not a defect).' }
        @{ Property = 'EtherSegmentedControl.BorderThickness'; Bucket = 'design-system-owned'; Reason = 'Appearance property (Background/Border*/CornerRadius/Padding/Foreground/Font*/CharacterSpacing/*ContentAlignment family); no {TemplateBinding BorderThickness} in src/Ether.DesignSystem.Controls/Controls/Inputs/EtherSegmentedControl.xaml - the design system deliberately does not let consumers override this to keep the visual language consistent across every app that consumes it (no visible effect is a FEATURE here, not a defect).' }
        @{ Property = 'EtherSegmentedControl.CharacterSpacing'; Bucket = 'design-system-owned'; Reason = 'Appearance property (Background/Border*/CornerRadius/Padding/Foreground/Font*/CharacterSpacing/*ContentAlignment family); no {TemplateBinding CharacterSpacing} in src/Ether.DesignSystem.Controls/Controls/Inputs/EtherSegmentedControl.xaml - the design system deliberately does not let consumers override this to keep the visual language consistent across every app that consumes it (no visible effect is a FEATURE here, not a defect).' }
        @{ Property = 'EtherSegmentedControl.CompositeMode'; Bucket = 'platform-noop'; Reason = 'Low-level UIElement rendering DP (CompositeMode) with no template consumption in src/Ether.DesignSystem.Controls/Controls/Inputs/EtherSegmentedControl.xaml and no consumer-visible effect; not something a consumer would reasonably expect to set.' }
        @{ Property = 'EtherSegmentedControl.CornerRadius'; Bucket = 'design-system-owned'; Reason = 'Appearance property (Background/Border*/CornerRadius/Padding/Foreground/Font*/CharacterSpacing/*ContentAlignment family); no {TemplateBinding CornerRadius} in src/Ether.DesignSystem.Controls/Controls/Inputs/EtherSegmentedControl.xaml - the design system deliberately does not let consumers override this to keep the visual language consistent across every app that consumes it (no visible effect is a FEATURE here, not a defect).' }
        @{ Property = 'EtherSegmentedControl.FontFamily'; Bucket = 'consumed-visually-stable'; Reason = '{TemplateBinding FontFamily} is present in src/Ether.DesignSystem.Controls/Controls/Inputs/EtherSegmentedControl.xaml:249 - the property IS consumed by the template. The visual gate observed no pixel change under its test conditions; that reflects the probe''s conditions, not a lack of wiring. NOT silently ineffective.' }
        @{ Property = 'EtherSegmentedControl.FontSize'; Bucket = 'consumed-visually-stable'; Reason = '{TemplateBinding FontSize} is present in src/Ether.DesignSystem.Controls/Controls/Inputs/EtherSegmentedControl.xaml:250 - the property IS consumed by the template. The visual gate observed no pixel change under its test conditions; that reflects the probe''s conditions, not a lack of wiring. NOT silently ineffective.' }
        @{ Property = 'EtherSegmentedControl.FontStretch'; Bucket = 'design-system-owned'; Reason = 'Appearance property (Background/Border*/CornerRadius/Padding/Foreground/Font*/CharacterSpacing/*ContentAlignment family); no {TemplateBinding FontStretch} in src/Ether.DesignSystem.Controls/Controls/Inputs/EtherSegmentedControl.xaml - the design system deliberately does not let consumers override this to keep the visual language consistent across every app that consumes it (no visible effect is a FEATURE here, not a defect).' }
        @{ Property = 'EtherSegmentedControl.Foreground'; Bucket = 'design-system-owned'; Reason = 'Appearance property (Background/Border*/CornerRadius/Padding/Foreground/Font*/CharacterSpacing/*ContentAlignment family); no {TemplateBinding Foreground} in src/Ether.DesignSystem.Controls/Controls/Inputs/EtherSegmentedControl.xaml - the design system deliberately does not let consumers override this to keep the visual language consistent across every app that consumes it (no visible effect is a FEATURE here, not a defect).' }
        @{ Property = 'EtherSegmentedControl.HorizontalContentAlignment'; Bucket = 'consumed-visually-stable'; Reason = '{TemplateBinding HorizontalContentAlignment} is present in src/Ether.DesignSystem.Controls/Controls/Inputs/EtherSegmentedControl.xaml:143 - the property IS consumed by the template. The visual gate observed no pixel change under its test conditions; that reflects the probe''s conditions, not a lack of wiring. NOT silently ineffective.' }
        @{ Property = 'EtherSegmentedControl.VerticalContentAlignment'; Bucket = 'consumed-visually-stable'; Reason = '{TemplateBinding VerticalContentAlignment} is present in src/Ether.DesignSystem.Controls/Controls/Inputs/EtherSegmentedControl.xaml:144 - the property IS consumed by the template. The visual gate observed no pixel change under its test conditions; that reflects the probe''s conditions, not a lack of wiring. NOT silently ineffective.' }

        # EtherSlider
        @{ Property = 'EtherSlider.Background'; Bucket = 'design-system-owned'; Reason = 'Appearance property (Background/Border*/CornerRadius/Padding/Foreground/Font*/CharacterSpacing/*ContentAlignment family); no {TemplateBinding Background} in src/Ether.DesignSystem.Controls/Controls/Inputs/EtherSlider.xaml - the design system deliberately does not let consumers override this to keep the visual language consistent across every app that consumes it (no visible effect is a FEATURE here, not a defect).' }
        @{ Property = 'EtherSlider.BackgroundSizing'; Bucket = 'platform-noop'; Reason = 'Low-level rendering DP; not referenced via TemplateBinding in src/Ether.DesignSystem.Controls/Controls/Inputs/EtherSlider.xaml, so no consumer value written to the control''s own BackgroundSizing property ever reaches rendering. Not part of the design system''s owned appearance surface and not something a consumer would reasonably expect to customize (unlike Background/BorderBrush/CornerRadius, which are visible identity choices).' }
        @{ Property = 'EtherSlider.BorderBrush'; Bucket = 'design-system-owned'; Reason = 'Appearance property (Background/Border*/CornerRadius/Padding/Foreground/Font*/CharacterSpacing/*ContentAlignment family); no {TemplateBinding BorderBrush} in src/Ether.DesignSystem.Controls/Controls/Inputs/EtherSlider.xaml - the design system deliberately does not let consumers override this to keep the visual language consistent across every app that consumes it (no visible effect is a FEATURE here, not a defect).' }
        @{ Property = 'EtherSlider.BorderThickness'; Bucket = 'design-system-owned'; Reason = 'Appearance property (Background/Border*/CornerRadius/Padding/Foreground/Font*/CharacterSpacing/*ContentAlignment family); no {TemplateBinding BorderThickness} in src/Ether.DesignSystem.Controls/Controls/Inputs/EtherSlider.xaml - the design system deliberately does not let consumers override this to keep the visual language consistent across every app that consumes it (no visible effect is a FEATURE here, not a defect).' }
        @{ Property = 'EtherSlider.CharacterSpacing'; Bucket = 'design-system-owned'; Reason = 'Appearance property (Background/Border*/CornerRadius/Padding/Foreground/Font*/CharacterSpacing/*ContentAlignment family); no {TemplateBinding CharacterSpacing} in src/Ether.DesignSystem.Controls/Controls/Inputs/EtherSlider.xaml - the design system deliberately does not let consumers override this to keep the visual language consistent across every app that consumes it (no visible effect is a FEATURE here, not a defect).' }
        @{ Property = 'EtherSlider.Clip'; Bucket = 'platform-noop'; Reason = 'Low-level UIElement rendering DP (Clip) with no template consumption in src/Ether.DesignSystem.Controls/Controls/Inputs/EtherSlider.xaml and no consumer-visible effect; not something a consumer would reasonably expect to set.' }
        @{ Property = 'EtherSlider.CompositeMode'; Bucket = 'platform-noop'; Reason = 'Low-level UIElement rendering DP (CompositeMode) with no template consumption in src/Ether.DesignSystem.Controls/Controls/Inputs/EtherSlider.xaml and no consumer-visible effect; not something a consumer would reasonably expect to set.' }
        @{ Property = 'EtherSlider.CornerRadius'; Bucket = 'design-system-owned'; Reason = 'Appearance property (Background/Border*/CornerRadius/Padding/Foreground/Font*/CharacterSpacing/*ContentAlignment family); no {TemplateBinding CornerRadius} in src/Ether.DesignSystem.Controls/Controls/Inputs/EtherSlider.xaml - the design system deliberately does not let consumers override this to keep the visual language consistent across every app that consumes it (no visible effect is a FEATURE here, not a defect).' }
        @{ Property = 'EtherSlider.FontFamily'; Bucket = 'design-system-owned'; Reason = 'Appearance property (Background/Border*/CornerRadius/Padding/Foreground/Font*/CharacterSpacing/*ContentAlignment family); no {TemplateBinding FontFamily} in src/Ether.DesignSystem.Controls/Controls/Inputs/EtherSlider.xaml - the design system deliberately does not let consumers override this to keep the visual language consistent across every app that consumes it (no visible effect is a FEATURE here, not a defect).' }
        @{ Property = 'EtherSlider.FontSize'; Bucket = 'design-system-owned'; Reason = 'Appearance property (Background/Border*/CornerRadius/Padding/Foreground/Font*/CharacterSpacing/*ContentAlignment family); no {TemplateBinding FontSize} in src/Ether.DesignSystem.Controls/Controls/Inputs/EtherSlider.xaml - the design system deliberately does not let consumers override this to keep the visual language consistent across every app that consumes it (no visible effect is a FEATURE here, not a defect).' }
        @{ Property = 'EtherSlider.FontStretch'; Bucket = 'design-system-owned'; Reason = 'Appearance property (Background/Border*/CornerRadius/Padding/Foreground/Font*/CharacterSpacing/*ContentAlignment family); no {TemplateBinding FontStretch} in src/Ether.DesignSystem.Controls/Controls/Inputs/EtherSlider.xaml - the design system deliberately does not let consumers override this to keep the visual language consistent across every app that consumes it (no visible effect is a FEATURE here, not a defect).' }
        @{ Property = 'EtherSlider.FontWeight'; Bucket = 'design-system-owned'; Reason = 'Appearance property (Background/Border*/CornerRadius/Padding/Foreground/Font*/CharacterSpacing/*ContentAlignment family); no {TemplateBinding FontWeight} in src/Ether.DesignSystem.Controls/Controls/Inputs/EtherSlider.xaml - the design system deliberately does not let consumers override this to keep the visual language consistent across every app that consumes it (no visible effect is a FEATURE here, not a defect).' }
        @{ Property = 'EtherSlider.Foreground'; Bucket = 'design-system-owned'; Reason = 'Appearance property (Background/Border*/CornerRadius/Padding/Foreground/Font*/CharacterSpacing/*ContentAlignment family); no {TemplateBinding Foreground} in src/Ether.DesignSystem.Controls/Controls/Inputs/EtherSlider.xaml - the design system deliberately does not let consumers override this to keep the visual language consistent across every app that consumes it (no visible effect is a FEATURE here, not a defect).' }
        @{ Property = 'EtherSlider.HorizontalContentAlignment'; Bucket = 'design-system-owned'; Reason = 'Appearance property (Background/Border*/CornerRadius/Padding/Foreground/Font*/CharacterSpacing/*ContentAlignment family); no {TemplateBinding HorizontalContentAlignment} in src/Ether.DesignSystem.Controls/Controls/Inputs/EtherSlider.xaml - the design system deliberately does not let consumers override this to keep the visual language consistent across every app that consumes it (no visible effect is a FEATURE here, not a defect).' }
        @{ Property = 'EtherSlider.Padding'; Bucket = 'design-system-owned'; Reason = 'Appearance property (Background/Border*/CornerRadius/Padding/Foreground/Font*/CharacterSpacing/*ContentAlignment family); no {TemplateBinding Padding} in src/Ether.DesignSystem.Controls/Controls/Inputs/EtherSlider.xaml - the design system deliberately does not let consumers override this to keep the visual language consistent across every app that consumes it (no visible effect is a FEATURE here, not a defect).' }
        @{ Property = 'EtherSlider.VerticalContentAlignment'; Bucket = 'design-system-owned'; Reason = 'Appearance property (Background/Border*/CornerRadius/Padding/Foreground/Font*/CharacterSpacing/*ContentAlignment family); no {TemplateBinding VerticalContentAlignment} in src/Ether.DesignSystem.Controls/Controls/Inputs/EtherSlider.xaml - the design system deliberately does not let consumers override this to keep the visual language consistent across every app that consumes it (no visible effect is a FEATURE here, not a defect).' }

        # EtherSteeringBar
        @{ Property = 'EtherSteeringBar.Background'; Bucket = 'design-system-owned'; Reason = 'Appearance property (Background/Border*/CornerRadius/Padding/Foreground/Font*/CharacterSpacing/*ContentAlignment family); no {TemplateBinding Background} in src/Ether.DesignSystem.Controls/Controls/Inputs/EtherSteeringBar.xaml - the design system deliberately does not let consumers override this to keep the visual language consistent across every app that consumes it (no visible effect is a FEATURE here, not a defect).' }
        @{ Property = 'EtherSteeringBar.BackgroundSizing'; Bucket = 'platform-noop'; Reason = 'Low-level rendering DP; not referenced via TemplateBinding in src/Ether.DesignSystem.Controls/Controls/Inputs/EtherSteeringBar.xaml, so no consumer value written to the control''s own BackgroundSizing property ever reaches rendering. Not part of the design system''s owned appearance surface and not something a consumer would reasonably expect to customize (unlike Background/BorderBrush/CornerRadius, which are visible identity choices).' }
        @{ Property = 'EtherSteeringBar.BorderBrush'; Bucket = 'design-system-owned'; Reason = 'Appearance property (Background/Border*/CornerRadius/Padding/Foreground/Font*/CharacterSpacing/*ContentAlignment family); no {TemplateBinding BorderBrush} in src/Ether.DesignSystem.Controls/Controls/Inputs/EtherSteeringBar.xaml - the design system deliberately does not let consumers override this to keep the visual language consistent across every app that consumes it (no visible effect is a FEATURE here, not a defect).' }
        @{ Property = 'EtherSteeringBar.BorderThickness'; Bucket = 'design-system-owned'; Reason = 'Appearance property (Background/Border*/CornerRadius/Padding/Foreground/Font*/CharacterSpacing/*ContentAlignment family); no {TemplateBinding BorderThickness} in src/Ether.DesignSystem.Controls/Controls/Inputs/EtherSteeringBar.xaml - the design system deliberately does not let consumers override this to keep the visual language consistent across every app that consumes it (no visible effect is a FEATURE here, not a defect).' }
        @{ Property = 'EtherSteeringBar.CharacterSpacing'; Bucket = 'design-system-owned'; Reason = 'Appearance property (Background/Border*/CornerRadius/Padding/Foreground/Font*/CharacterSpacing/*ContentAlignment family); no {TemplateBinding CharacterSpacing} in src/Ether.DesignSystem.Controls/Controls/Inputs/EtherSteeringBar.xaml - the design system deliberately does not let consumers override this to keep the visual language consistent across every app that consumes it (no visible effect is a FEATURE here, not a defect).' }
        @{ Property = 'EtherSteeringBar.Clip'; Bucket = 'platform-noop'; Reason = 'Low-level UIElement rendering DP (Clip) with no template consumption in src/Ether.DesignSystem.Controls/Controls/Inputs/EtherSteeringBar.xaml and no consumer-visible effect; not something a consumer would reasonably expect to set.' }
        @{ Property = 'EtherSteeringBar.CompositeMode'; Bucket = 'platform-noop'; Reason = 'Low-level UIElement rendering DP (CompositeMode) with no template consumption in src/Ether.DesignSystem.Controls/Controls/Inputs/EtherSteeringBar.xaml and no consumer-visible effect; not something a consumer would reasonably expect to set.' }
        @{ Property = 'EtherSteeringBar.CornerRadius'; Bucket = 'design-system-owned'; Reason = 'Appearance property (Background/Border*/CornerRadius/Padding/Foreground/Font*/CharacterSpacing/*ContentAlignment family); no {TemplateBinding CornerRadius} in src/Ether.DesignSystem.Controls/Controls/Inputs/EtherSteeringBar.xaml - the design system deliberately does not let consumers override this to keep the visual language consistent across every app that consumes it (no visible effect is a FEATURE here, not a defect).' }
        @{ Property = 'EtherSteeringBar.FontFamily'; Bucket = 'design-system-owned'; Reason = 'Appearance property (Background/Border*/CornerRadius/Padding/Foreground/Font*/CharacterSpacing/*ContentAlignment family); no {TemplateBinding FontFamily} in src/Ether.DesignSystem.Controls/Controls/Inputs/EtherSteeringBar.xaml - the design system deliberately does not let consumers override this to keep the visual language consistent across every app that consumes it (no visible effect is a FEATURE here, not a defect).' }
        @{ Property = 'EtherSteeringBar.FontSize'; Bucket = 'design-system-owned'; Reason = 'Appearance property (Background/Border*/CornerRadius/Padding/Foreground/Font*/CharacterSpacing/*ContentAlignment family); no {TemplateBinding FontSize} in src/Ether.DesignSystem.Controls/Controls/Inputs/EtherSteeringBar.xaml - the design system deliberately does not let consumers override this to keep the visual language consistent across every app that consumes it (no visible effect is a FEATURE here, not a defect).' }
        @{ Property = 'EtherSteeringBar.FontStretch'; Bucket = 'design-system-owned'; Reason = 'Appearance property (Background/Border*/CornerRadius/Padding/Foreground/Font*/CharacterSpacing/*ContentAlignment family); no {TemplateBinding FontStretch} in src/Ether.DesignSystem.Controls/Controls/Inputs/EtherSteeringBar.xaml - the design system deliberately does not let consumers override this to keep the visual language consistent across every app that consumes it (no visible effect is a FEATURE here, not a defect).' }
        @{ Property = 'EtherSteeringBar.FontWeight'; Bucket = 'design-system-owned'; Reason = 'Appearance property (Background/Border*/CornerRadius/Padding/Foreground/Font*/CharacterSpacing/*ContentAlignment family); no {TemplateBinding FontWeight} in src/Ether.DesignSystem.Controls/Controls/Inputs/EtherSteeringBar.xaml - the design system deliberately does not let consumers override this to keep the visual language consistent across every app that consumes it (no visible effect is a FEATURE here, not a defect).' }
        @{ Property = 'EtherSteeringBar.Foreground'; Bucket = 'design-system-owned'; Reason = 'Appearance property (Background/Border*/CornerRadius/Padding/Foreground/Font*/CharacterSpacing/*ContentAlignment family); no {TemplateBinding Foreground} in src/Ether.DesignSystem.Controls/Controls/Inputs/EtherSteeringBar.xaml - the design system deliberately does not let consumers override this to keep the visual language consistent across every app that consumes it (no visible effect is a FEATURE here, not a defect).' }
        @{ Property = 'EtherSteeringBar.HorizontalContentAlignment'; Bucket = 'design-system-owned'; Reason = 'Appearance property (Background/Border*/CornerRadius/Padding/Foreground/Font*/CharacterSpacing/*ContentAlignment family); no {TemplateBinding HorizontalContentAlignment} in src/Ether.DesignSystem.Controls/Controls/Inputs/EtherSteeringBar.xaml - the design system deliberately does not let consumers override this to keep the visual language consistent across every app that consumes it (no visible effect is a FEATURE here, not a defect).' }
        @{ Property = 'EtherSteeringBar.VerticalContentAlignment'; Bucket = 'design-system-owned'; Reason = 'Appearance property (Background/Border*/CornerRadius/Padding/Foreground/Font*/CharacterSpacing/*ContentAlignment family); no {TemplateBinding VerticalContentAlignment} in src/Ether.DesignSystem.Controls/Controls/Inputs/EtherSteeringBar.xaml - the design system deliberately does not let consumers override this to keep the visual language consistent across every app that consumes it (no visible effect is a FEATURE here, not a defect).' }
    )

    # Control -> ControlTemplate file map used by scripts/Verify-SilentPropertyCoverage.ps1 to run
    # the SAME TemplateBinding cross-check scripts/Verify-UnsupportedProperties.ps1 already runs
    # for the 12 closed-list Entries above, but against every AcknowledgedSilent entry too. This is
    # what makes the 'design-system-owned' / 'consumed-visually-stable' labels self-verifying
    # instead of merely asserted: the gate re-derives, from the template file text, whether each
    # entry's TemplateBinding claim is actually true, and fails if a label disagrees with reality.
    # EtherSegmentPanel is deliberately absent: it is a Panel (FrameworkElement subclass), not a
    # templated Control, so there is no ControlTemplate file to check it against - both of its
    # AcknowledgedSilent entries are 'platform-noop', a bucket the gate does not TemplateBinding-
    # check, so this is not a gap.
    TemplateFiles = @{
        EtherButton              = 'src/Ether.DesignSystem.Controls/Controls/Inputs/EtherButton.xaml'
        EtherCheckbox            = 'src/Ether.DesignSystem.Controls/Controls/Inputs/EtherCheckbox.xaml'
        EtherDropdown            = 'src/Ether.DesignSystem.Controls/Controls/Inputs/EtherDropdown.xaml'
        EtherInput               = 'src/Ether.DesignSystem.Controls/Controls/Inputs/EtherInput.xaml'
        EtherIntelligenceButton  = 'src/Ether.DesignSystem.Controls/Controls/Inputs/EtherIntelligenceButton.xaml'
        EtherMasthead            = 'src/Ether.DesignSystem.Controls/Controls/Navigation/EtherMasthead.xaml'
        EtherProgressBar         = 'src/Ether.DesignSystem.Controls/Controls/Inputs/EtherProgressBar.xaml'
        EtherRadioButton         = 'src/Ether.DesignSystem.Controls/Controls/Inputs/EtherRadioButton.xaml'
        EtherSegmentedControl    = 'src/Ether.DesignSystem.Controls/Controls/Inputs/EtherSegmentedControl.xaml'
        EtherSlider              = 'src/Ether.DesignSystem.Controls/Controls/Inputs/EtherSlider.xaml'
        EtherSteeringBar         = 'src/Ether.DesignSystem.Controls/Controls/Inputs/EtherSteeringBar.xaml'
    }
}
